# Generated by Django 3.1 on 2020-08-31 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_auto_20200831_0914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='updated_on',
        ),
    ]
